apiVersion: v1
kind: List
items:
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      name: tars-es-common-services
      labels:
        template: logstash
      annotations:
        template.openshift.io/expose-uri: "http://{.spec.host}{.spec.path}"
    spec:
      tls:
        termination: edge
      to:
        kind: Service
        name: tars-es-common-services

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tars-es-common-services
      labels:
        template: logstash
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: tars-es-common-services
      template:
        metadata:
          labels:
            app: tars-es-common-services
        spec:
          containers:
            - name: tars-es-common-services
              image: image-registry.openshift-image-registry.svc:5000/tars-images/tars-es-common-services:f3305b5
              imagePullPolicy: Always
              ports:
                - containerPort: 9092
              envFrom:
                - secretRef:
                    name: tars-es-common-services-es
              resources:
                limits:
                  cpu: "1"
                  memory: "1Gi"
                requests:
                  cpu: "1"
                  memory: "1Gi"

  - apiVersion: v1
    kind: Service
    metadata:
      name: tars-es-common-services
      labels:
        template: logstash
    spec:
      ports:
        - name: tars-es-common-services
          port: 80
          protocol: TCP
          targetPort: 9092
      selector:
        app: tars-es-common-services
