apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: tkn-1
  name: hello-world-nginx
  annotations: {}
spec:
  selector:
    matchLabels:
      app: hello-world-nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world-nginx
    spec:
      containers:
        - name: container
          image: image-registry.openshift-image-registry.svc:5000/openshift/httpd:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          env: []
      imagePullSecrets: []
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  paused: false


---

apiVersion: v1
kind: Service
metadata:
  name: hello-world-nginx
spec:
  internalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world-nginx
  sessionAffinity: None
  type: ClusterIP
status:

